name: kplay
description: "KPlay - A Jukebox for the Raspberry Pi"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  marquee: ^2.3.0
  path: any
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
